### ISSUE TITLE
Class "CacheWerk\Relay\Credis\RelayCredisAdapter" missing

### ISSUE THREAD

**Issue by amjadm61** [cachewerk/magento-relay#1]
Class is missing in the repo
Fatal error: Uncaught Error: Class "CacheWerk\Relay\Credis\RelayCredisAdapter" not found in app/code/CacheWerk/Relay/Cache/Backend/Relay.php:52

**Comment by tillkruss** [comment]
We just tagged v0.1.1 that brings this package up to speed with Relay 0.5.0.

https://github.com/cachewerk/magento-relay/releases/tag/v0.1.1
